### ISSUE TITLE
Backend API for requests for donors

### ISSUE THREAD

**Issue by AshTS** [UMM-CSci-3601-S23/iteration-1-ash-gregory-chenfei-harry#15]
We need functionality for adding requests, updating requests, and deleting requests.

**Comment by AshTS** [comment]
To get started on this, we need to consider the values we want to store in the database. We want to keep some of the future stories in mind as well so we can try to future proof this design.

For now, I propose the following values for each request presented to the community:

- Item Name
- Item Category
- Unit
- Count
- Price
- Priority
- Date Added
- Date Updated
- Count Remaining

The item name is fairly self explanatory, and can be the name presented to the donors.

The item category is up for debate, for the moment, this can be left blank, and potentially converted over to the categories used by the submission form (Fruits, Vegetables, Proteins, Grains, Dairy, Pantry/Cooking/Baking, Baby, Personal,
Household, and Miscellaneous).

The unit is used to specify what unit the count values are in. For example, milk could be measured in gallons,  apples in items, and cereal in boxes.

The count is the number of the given unit of any item requested.

The price is a rough estimate of the price of one unit of the item in question. This is not immediately applicable, but can be used in some of the stories we pitched as future possibilities.

The priority is a number used to give a rough way for volunteers to order the requests by importance. Smaller numbers mean more highly prioritized.

Date added is the date the request was initially made, and date updated is the date the entry was last updated (for example an edit was made, or someone pledged to bring in some amount of the given item).

Count remaining is also used for the potential to have "pledges" update the amount requested that appears to donors.

**Comment by Harry58326** [comment]
This is how the clients get all the request by request API which is server.get("/api/requests", requestController::getRequests);
